export const GET_INVOICES_LIST = "GET_INVOICES_LIST";
export const GET_INVOICE_DETAIL = "GET_INVOICE_DETAIL";
export const SAVE_INVOICE = "SAVE_INVOICE";
export const APPRVE_INVOICE = "APPRVE_INVOICE";
export const API_ERROR = "API_ERROR";
//-------CUSTOMER-------//
export const GET_CUSTOMERS_LIST ="GET_CUSTOMERS_LIST";
export const GET_CUSTOMER_DETAIL = "GET_CUSTOMER_DETAIL";
export const SAVE_CUSTOMER = "SAVE_CUSTOMER";



