export const GET_INVOICES_LIST = "GET_INVOICES_LIST";
export const GET_INVOICE_DETAIL = "GET_INVOICE_DETAIL";
export const SAVE_INVOICE = "SAVE_INVOICE";
export const APPRVE_INVOICE = "APPRVE_INVOICE";
export const API_ERROR = "API_ERROR";



exprot const GET_CUSTOMER_LIST = "GET_CUSTOMER_LIST";
exprot const GET_CUSTOMER_DETAIL = "GET_CUSTOMER_DETAIL";
exprot const SAVE_CUSTOMER = "SAVE_CUSTOMER";



